### ISSUE TITLE
Search delay (debounce)

### ISSUE THREAD

**Issue by gregzaal** [Poly-Haven/polyhaven.com#10]
300ms delay after keystroke to improve performance when searching on page with lots of results to filter.

**Comment by gregzaal** [comment]
Took a crack at this a while ago... it's not as trivial as I thought :)

**Comment by fulopkovacs** [comment]
This is a fun issue, I'll start working on it! :relaxed: Unfortunately, I don't have much time next week, so I'll be a bit slow.
