### ISSUE TITLE
WebGL previews for Textures & Models

### ISSUE THREAD

**Issue by gregzaal** [Poly-Haven/polyhaven.com#24]
We need a simple three.js/babylon GLTF viewer for all our Textures and 3D Models, [like this](https://gltf-viewer.donmccurdy.com/).

It should use our existing `.gltf` files and their associated textures, or if needed a pre-generated packed `.glb` file.

# Basic requirements:

* Load the existing 4K resolution gltf file
* PBR material support
* Lit with an HDRI environment

# Would be nice:

* Being able to toggle overlaid wireframes
* Allow switching between a few different HDRI environments
* View each texture map (diffuse, normal, etc.) independently on the model.
* Choose the texture resolution (usually we have 8k available, and it might also be helpful to see lower res too).

# Implementation:

Check out the `webgl-previews` branch where some placeholder code is added (`components/AssetPage/WebGL/GLTFViewer.tsx`) and the 3D Preview button is already added to the image carousel.

![2021-07-03_13-35-19](https://user-images.githubusercontent.com/5604661/124353340-2c88a800-dc06-11eb-9a66-7871c4200742.png)

The logic to fetch the gltf file info from our API is already there, including all the separate texture files it needs. The data returned looks like this:

```json
{
  "gltf": {
    "md5": "c96fcd14352a31ede83406a579ef47f1",
    "size": 3564,
    "url": "https://dl.polyhaven.com/file/ph-assets/Textures/gltf/4k/brick_wall_001/brick_wall_001_4k.gltf",
    "include": {
      "textures/brick_wall_001_diffuse_4k.jpg": {
        "md5": "f7af74a75eb4e90556345061f480dcc6",
        "size": 6544897,
        "url": "https://dl.polyhaven.com/file/ph-assets/Textures/jpg/4k/brick_wall_001/brick_wall_001_diffuse_4k.jpg"
      },
      "textures/brick_wall_001_rough_4k.jpg": {
        "url": "https://dl.polyhaven.com/file/ph-assets/Textures/jpg/4k/brick_wall_001/brick_wall_001_rough_4k.jpg",
        "size": 2849392,
        "md5": "99659a2a97f98cf3b67975cfdf4415b6"
      },
      "brick_wall_001.bin": {
        "md5": "658b6a4923dd1b90c42e0d0595957743",
        "url": "https://dl.polyhaven.com/file/ph-assets/Textures/gltf/8k/brick_wall_001/brick_wall_001.bin",
        "size": 2370100
      },
      "textures/brick_wall_001_nor_gl_4k.jpg": {
        "size": 11626189,
        "md5": "cd83376a035b781b319741d1a8207c07",
        "url": "https://dl.polyhaven.com/file/ph-assets/Textures/jpg/4k/brick_wall_001/brick_wall_001_nor_gl_4k.jpg"
      }
    }
  }
}
```

**Comment by chippieTV** [comment]
Hi there.. do you have a design for UI components etc? I have a part working prototype I put together for fun...

**Comment by gregzaal** [comment]
Nice work :) Can you make a PR? Seems like you've got the important stuff working already and we can push that first, then work on the fancy stuff incrementally.

CORS is not supposed to be an issue, the API and download urls shouldn't require any specific origin, but we had some caching issues with that a few days ago.

I think hiding and showing individual pieces is a cool idea, but practically it's not commonly needed (very few assets have more than one object), so I think it'll just add more UI clutter than it's worth.

I haven't made any UI mockups, but I can take care of UI styling once the functionality is there.

**Comment by chippieTV** [comment]
So I was trying to figure out getting CORS fixed from local, but can't get it working. I think loading files via scripts has different permissions than loading them into basic image tags etc. I'm going round in circles. Usually I'm working on long term projects where we dealt with CORS long ago, so I'm not so fresh with how we solve it (or learn to live with it).

It's late where I am (Tokyo) and work tomorrow so I later in the week I'll try setting up a simple standalone viewer and mock backend so I can work on the front without CORS issues.

I know there is another submission going on, but I'll keep on anyway. I really just wanted an excuse to dig around some different libraries and learn a bit outside my day to day stack.
