### ISSUE TITLE
Enable 16× anisotropic filtering on 3D previews to improve texture appearance at oblique angles

### ISSUE THREAD

**Issue by Calinou** [Poly-Haven/polyhaven.com#45]
On 3D model previews, textures currently look blurry at oblique angles. Example with https://polyhaven.com/a/wooden_crate_02:

## Firefox 98

*On Firefox, forcing anisotropic filtering on Linux doesn't seem to work.*

![image](https://user-images.githubusercontent.com/180032/163890599-0a67a9e7-2da7-4e5c-a726-38f716f8ea65.png)

If anisotropic texture filtering was enabled in the glTF viewer, it would look much better. Here's an example with anisotropic filtering forced in the NVIDIA Control Panel (`nvidia-settings` on Linux):

## Chromium 99 (with forced 16× anisotropic filtering at a driver level)

*Forcing anisotropic filtering works on that browser.*

![image](https://user-images.githubusercontent.com/180032/163890545-f7e84fb7-e9ad-4287-b0f0-219aed3359a5.png)

This also occurs on texture previews, although it's not as noticeable:

![image](https://user-images.githubusercontent.com/180032/163890354-19ea9981-4fe8-46ef-8984-0b91e1a47f5b.png)

This can be tested with a texture such as https://polyhaven.com/a/cobblestone_floor_05.

Enabling 16× anisotropic filtering has a small performance cost, but considering this is a 3D preview, high framerates aren't essential to have here.

**Comment by gregzaal** [comment]
That looks miles better yeah. Do you know where to enable this in the code?

**Comment by Calinou** [comment]
> That looks miles better yeah. Do you know where to enable this in the code?

I don't have experience with Three.js, so unfortunately not.

**Comment by gregzaal** [comment]
I've done some digging and it seems like three.js definitely supports anisotropic filtering, but I've tried setting it on each texture component and it can't seem to get it to work.
