### ISSUE TITLE
Setup local host with admin panel

### ISSUE THREAD

**Issue by vm32** [Poly-Haven/polyhaven.com#68]
I'm encountering difficulties logging into the admin page of the Polyhaven project and uploading my assets(locally). This issue prevents me from contributing to the project effectively and utilizing the platform to its full potential. Is there any way to use the admin page in the local host and if there is a way what is the admin's default login and password?

**Comment by gregzaal** [comment]
Hi there,

Unfortunately not, we haven't open-sourced the admin site yet as it's not meant to be used externally. 

If you're interested in contributing assets to Poly Haven, you can read about that process here: https://polyhaven.com/contribute
