### ISSUE TITLE
Inquiry about Your Open-Source Project's Backend Technology Stack

### ISSUE THREAD

**Issue by vm32** [Poly-Haven/polyhaven.com#69]
**Description:**
I've been closely following your open-source project and I'm interested in understanding the technologies and tools used to create it. I plan to build something similar for a specific purpose.

**Request:**
- Could you please provide insights or guidance on the technologies, frameworks, and key components used in your project?
- Specifically, I know you are using Firestore and Blaze B2, but I'm uncertain about how to create a CRUD (Create, Read, Update, Delete) application for it.

**Goal:**
My aim is to learn from your project and use it as a reference to build a customized solution. Any information or direction, especially regarding Firestore and Blaze B2, would be greatly appreciated.

Thank you for your assistance!

**Comment by gregzaal** [comment]
Hi there,

You can read about our web infrastructure here: https://blog.polyhaven.com/how-we-handle-80tb-and-5m-page-views-a-month-for-under-400/

Some numbers have gone up since writing that, but the overall architecture us the same.

**Comment by vm32** [comment]
@gregzaal, Thank you for sharing details about your web infrastructure, which is quite insightful.Specifically, I'm interested in understanding how your project handles CRUD operations and data management, given the extensive amount of data you work with. Could you provide insights or best practices on how you manage the creation, reading, updating, and deletion of data within your project, considering the scale and complexity you operate at?Any specific details or guidance in this regard would be tremendously helpful as I'm looking to implement similar functionality in my project.I appreciate your time and assistance.
