### ISSUE TITLE
Home page slider

### ISSUE THREAD

**Issue by gregzaal** [Poly-Haven/polyhaven.com#7]
Turn the top banner image on the home page into a gallery slider, showing multiple renders.

**Comment by mykongee** [comment]
Hi! I'd like to try tackling this if no one else is. One question I have is where do we source the images of the renders?
I see that currently in [Slider.module.scss#L7](https://github.com/Poly-Haven/polyhaven.com/blob/ebafa16c09ff82aeef7d5a99b34f52278e65fd86/components/Home/Slider/Slider.module.scss#L7) we can grab images from the cdn -- I was wondering if we could leverage something like the API to fetch renders to display in a slider. Please correct me if I'm wrong, but [the API](https://github.com/Poly-Haven/Public-API) seems to only offer `assets.`

Would the correct approach be something like taking https://cdn.polyhaven.com/gallery/cf9f35c80ae9d371fd30.jpg?width=1181 and hardcoding these into a carousel?

Alternatively, we could handpick certain renders to showcase in the carousel and serve them from the cdn. Would love to hear your thoughts!

**Comment by gregzaal** [comment]
For now I think hard-coded URLs is fine. Feel free to use any images to test with, I'll replace them with cherry picked renders before deployment :)
