### ISSUE TITLE
Site doesn't work due to minified react error #301

### ISSUE THREAD

**Issue by questionabl** [Poly-Haven/polyhaven.com#72]
Attempting to access "Assets", "Textures", "HDRIs" or "Models" results in the following error immediately after loading:
![Screenshot 2024-05-31 121905](https://github.com/Poly-Haven/polyhaven.com/assets/86056099/1f8197c5-2d9f-49b1-b34b-9d3487a78f2d)
This is consistent even after clearing all cached files relating to the site, and is consistent across Chrome and Firefox. I am using a PC running Windows 11.

**Comment by questionabl** [comment]
If any more details are needed, feel free to contact me.

**Comment by alexcaussades** [comment]
Hello,

Same for me on edge, with windows 11 

![image](https://github.com/Poly-Haven/polyhaven.com/assets/27455689/0dd992d8-a8b0-4e98-a294-2793c7123636)

**Comment by gregzaal** [comment]
Thanks for the report, the issue was fixed earlier today. If it's still broken for you, try Ctrl-F5 or Shift-F5.
